GET http://localhost:8080/api/messages
Accept: application/json

### le client IntelliJ ne marche pas avec les streams ! curl -H "${AUTH}" -X GET http://localhost:8080/api/messages/subscribe
GET http://localhost:8080/api/messages/subscribe
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmcmVkIiwicm9sZXMiOlsiVVNFUiJdLCJleHAiOjE1ODYwNjk1ODF9.2HVolRR3seI6grA7i0s9_GOixuEr5RGTJB-swBmSh7iwTbbeoALFZlyQrHmCkEH9XEWuJmTJet0_T26OqFUM5w

###
POST http://localhost:8080/api/messages
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmcmVkIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImV4cCI6MTU4NjE5MDM3NX0.8oX5FKGcPQ_iRIR7msWWtl-OtM-S9iYmn2UcgFSFcXFvf7XBYpyw4WiQTIACGkSblNQiDIje6M0sFBRctoZE_Q
Content-Type: application/json

{"texte":"Youpi ça marche !"}

###
POST http://localhost:8080/api/messages
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlVTRVIiLCJBRE1JTiIsIlJPTEVfQURNSU4iXSwiZXhwIjoxNTg2MTcxODAwfQ.Z-GJfUZ6EhHlAK6O6N53OBdogKZhqEeW1vVMXt03cbT_Clb6gmU9GmXP_XnJGkECupeY9MvbFpCCNu-SC-Buqg
Content-Type: application/json

{"texte":"On se calme ! vos papiers !"}

###
GET http://localhost:8080/api/messages/5


###
DELETE http://localhost:8080/api/messages/1

### curl -i -s -X POST -H 'Content-Type: application/json' --data '{"username":"fred","password":"fred"}' http://localhost:8080/auth/login
### AUTH=$(curl -i -s -X POST -H 'Content-Type: application/json' --data '{"username":"fred","password":"fred"}' http://localhost:8080/auth/login | grep "Authorization:")
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "fred",
  "password": "fred"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
POST http://localhost:8080/api/utilisateurs
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwiZXhwIjoxNTg2MTkwNDY4fQ.Q-KhU0Hl3LXEs8QALlm29ELmvi4nUhZGd_1ZHZvwhi92lEGG9VmxOZykZtfkSEIak2kWtipPJuf7kxQTI9aQRw
Content-Type: application/json

{"login":"yohan", "password":"yohan"}
###

